repos:
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: 7e989a3cc4995a63e37b6a0211865e2529663f2f
      hooks:
        - id: pretty-format-java
          args: [ --autofix ]