package com.xp.samplecustomview.feature.galleryoffeatures.models

import com.xp.samplecustomview.feature.recyclerview.features.hierarchical.feature.composite.view.fragments.TwoListDepartmentsPersistentBottomSheetFragment

class BindItemTwoListDepartmentsPersistentBottomSheet(channel: ListenerListFragments) :
    BindItemFeatureDefaultForFragment(channel, TwoListDepartmentsPersistentBottomSheetFragment.newInstance())
